### ISSUE TITLE
panic in rudder-server v1.7.3

### ISSUE THREAD

**Issue by cvlendistry** [rudderlabs/rudder-server#3707]
2023-07-27T22:38:34.647Z	ERROR	jobsdb.batch_rt	jobsdb/jobsdb.go:510	batch_rtmap[{batch_rt_jobs_5254 batch_rt_job_status_5254 5254}:map[LendistryRudderWorkspace:map[RS:map[RS_RS:map[executing:{Has Jobs 2023-07-27 22:38:06.815959075 +0000 UTC m=+393.387165799} not_picked_yet:{Has Jobs 2023-07-27 22:38:20.877600114 +0000 UTC m=+407.448806839} succeeded:{Has Jobs 2023-07-27 22:38:07.179049073 +0000 UTC m=+393.750255811}] destination_id_1y1WAwGCLWXTBybX0rdLwzDpydV:map[executing:{Has Jobs 2023-07-27 22:38:06.815958403 +0000 UTC m=+393.387165139} not_picked_yet:{Has Jobs 2023-07-27 22:38:20.877599269 +0000 UTC m=+407.448805993} succeeded:{Has Jobs 2023-07-27 22:38:07.179048294 +0000 UTC m=+393.750255032}]]] _all_:map[RS:map[RS_RS:map[executing:{Has Jobs 2023-07-27 22:38:06.815962474 +0000 UTC m=+393.387169199} failed:{No Jobs 2023-07-27 22:38:06.769127195 +0000 UTC m=+393.340333933} not_picked_yet:{Has Jobs 2023-07-27 22:38:20.877596843 +0000 UTC m=+407.448803568} succeeded:{Has Jobs 2023-07-27 22:38:07.179052946 +0000 UTC m=+393.750259684}] destination_id_1y1WAwGCLWXTBybX0rdLwzDpydV:map[executing:{Has Jobs 2023-07-27 22:38:06.815961847 +0000 UTC m=+393.387168584} failed:{No Jobs 2023-07-27 22:38:06.769126535 +0000 UTC m=+393.340333275} not_picked_yet:{Has Jobs 2023-07-27 22:38:20.877595912 +0000 UTC m=+407.448802655} succeeded:{Has Jobs 2023-07-27 22:38:07.179052265 +0000 UTC m=+393.750259002}]]]] {batch_rt_jobs_5255 batch_rt_job_status_5255 5255}:map[LendistryRudderWorkspace:map[RS:map[RS_RS:map[not_picked_yet:{Has Jobs 2023-07-27 22:38:29.711858003 +0000 UTC m=+416.283064740}] destination_id_1y1WAwGCLWXTBybX0rdLwzDpydV:map[not_picked_yet:{Has Jobs 2023-07-27 22:38:29.711857654 +0000 UTC m=+416.283064391}]]] _all_:map[RS:map[RS_RS:map[not_picked_yet:{Has Jobs 2023-07-27 22:38:29.711854974 +0000 UTC m=+416.283061711}] destination_id_1y1WAwGCLWXTBybX0rdLwzDpydV:map[not_picked_yet:{Has Jobs 2023-07-27 22:38:29.711852782 +0000 UTC m=+416.283059520}]]]]]
2023-07-27T22:38:34.647Z	ERROR	jobsdb.batch_rt	jobsdb/jobsdb.go:510	goroutine 836 [running]:
github.com/rudderlabs/rudder-server/utils/logger.(*logger).Fatal(0xc000ebf860, {0xc000e72330?, 0x0?, 0xc0029f4b40?})
	/rudder-server/utils/logger/logger.go:186 +0x92
github.com/rudderlabs/rudder-server/jobsdb.(*HandleT).assertError(0xc001267b00, {0x3013e80, 0xc0029f4b40})
	/rudder-server/jobsdb/migration.go:418 +0x239
github.com/rudderlabs/rudder-server/jobsdb.(*HandleT).getMigrationList(0xc001267b00, {0xc0055c1860, 0x2, 0x2})
	/rudder-server/jobsdb/migration.go:276 +0x291
github.com/rudderlabs/rudder-server/jobsdb.(*HandleT).migrateDSLoop(0xc001267b00, {0x3033ad0, 0xc00178f130})
github.com/rudderlabs/rudder-server/jobsdb.(*HandleT).startMigrateDSLoop.func1()
	/rudder-server/jobsdb/migration.go:26 +0x25
github.com/rudderlabs/rudder-server/utils/misc.WithBugsnag.func1()
	/rudder-server/utils/misc/misc.go:1183 +0x70
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
2023-07-27T22:38:34.647Z	ERROR	utils.misc	misc/misc.go:1172	pq: relation "batch_rt_jobs_5254" does not exist
2023-07-27T22:38:34.648Z	ERROR	utils.misc	misc/misc.go:1172	goroutine 836 [running]:
panic: pq: relation "batch_rt_jobs_5254" does not exist [recovered]
	panic: pq: relation "batch_rt_jobs_5254" does not exist [recovered]
	panic: pq: relation "batch_rt_jobs_5254" does not exist
goroutine 836 [running]:
github.com/bugsnag/bugsnag-go/v2.AutoNotify({0xc002cbd530, 0x3, 0xc0000a0000?})
panic({0x2667ee0, 0xc0029f4b40})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/rudderlabs/rudder-server/utils/misc.BugsnagNotify.func1.1()
	/rudder-server/utils/misc/misc.go:1173 +0x35c
sync.(*Once).doSlow(0x0?, 0xc002cbd818?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/rudderlabs/rudder-server/utils/misc.BugsnagNotify.func1()
	/rudder-server/utils/misc/misc.go:1162 +0xbc
panic({0x2667ee0, 0xc0029f4b40})
github.com/rudderlabs/rudder-server/jobsdb.(*HandleT).assertError(0xc001267b00, {0x3013e80, 0xc0029f4b40})
github.com/rudderlabs/rudder-server/jobsdb.(*HandleT).checkIfMigrateDS(0xc001267b00, {{0xc0017d2dc8, 0x12}, {0xc0017d2de0, 0x18}, {0xc0017d2dd6, 0x4}})

**Comment by gitcommitshow** [comment]
Hi @cvlendistry , apologies for the delayed response. Did you find the solution to the issue?
If not, please provide more context such as which version of rudder-server are you using and how can it be reproduced?

Btw, I remember similar issue was reported in #support channel in [RudderStack Slack Community](https://www.rudderstack.com/join-rudderstack-slack-community/), and the solution was to upgrade the version where that bug was resolved.
