### ISSUE TITLE
Startup error if another user connected to postgres DB

### ISSUE THREAD

**Issue by caseylucas** [rudderlabs/rudder-server#658]
I noticed this error in the rudder-server logs:

```
panic: pq: must be a member of the role whose process is being terminated or member of pg_signal_backend [recovered]
	panic: pq: must be a member of the role whose process is being terminated or member of pg_signal_backend [recovered]
	panic: pq: must be a member of the role whose process is being terminated or member of pg_signal_backend

goroutine 42 [running]:
github.com/bugsnag/bugsnag-go.AutoNotify(0xc00060bab0, 0x3, 0x3)
	/codebuild/output/src393278594/src/github.com/rudderlabs/rudder-server/vendor/github.com/bugsnag/bugsnag-go/bugsnag.go:109 +0x2bc
panic(0x15810c0, 0xc0001dc000)
	/root/.goenv/versions/1.13.8/src/runtime/panic.go:679 +0x1b2
github.com/rudderlabs/rudder-server/rruntime.Go.func1.1(0x1b77220, 0xc0004836e0)
	/codebuild/output/src393278594/src/github.com/rudderlabs/rudder-server/rruntime/goroutine-factory.go:43 +0x39a
panic(0x15810c0, 0xc0001dc000)
	/root/.goenv/versions/1.13.8/src/runtime/panic.go:679 +0x1b2
github.com/rudderlabs/rudder-server/jobsdb.(*HandleT).assertError(0xc00000a1e0, 0x1b4eae0, 0xc0001dc000)
	/codebuild/output/src393278594/src/github.com/rudderlabs/rudder-server/jobsdb/jobsdb.go:210 +0xe6
github.com/rudderlabs/rudder-server/jobsdb.(*HandleT).terminateQueries(0xc00000a1e0)
	/codebuild/output/src393278594/src/github.com/rudderlabs/rudder-server/jobsdb/jobsdb.go:1174 +0x2f1
github.com/rudderlabs/rudder-server/jobsdb.(*HandleT).Setup(0xc00000a1e0, 0xc0001c4300, 0x1792418, 0x2, 0x0, 0x0, 0x0, 0x0)
	/codebuild/output/src393278594/src/github.com/rudderlabs/rudder-server/jobsdb/jobsdb.go:424 +0x37d
main.startRudderCore(0xc0001c4338, 0xc000480000)
	/codebuild/output/src393278594/src/github.com/rudderlabs/rudder-server/main.go:186 +0x255
main.main.func4()
	/codebuild/output/src393278594/src/github.com/rudderlabs/rudder-server/main.go:340 +0x3d
github.com/rudderlabs/rudder-server/rruntime.Go.func1(0xc0005a2530)
	/codebuild/output/src393278594/src/github.com/rudderlabs/rudder-server/rruntime/goroutine-factory.go:46 +0x81
created by github.com/rudderlabs/rudder-server/rruntime.Go
	/codebuild/output/src393278594/src/github.com/rudderlabs/rudder-server/rruntime/goroutine-factory.go:32 +0x3f
```

Reproduce by being logged into the postgres DB with a different user id when rudder-server starts up.

The problem is that the query used to execute `pg_terminate_backend` does not correctly filter from `pg_stat_activity`. I was logged into the DB with a different user and this statement attempts to terminate sessions that the calling user does not control:

```
sqlStatement := fmt.Sprintf("SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE datname = '%s' AND pid <> pg_backend_pid()", dbname)
```
Original source: https://github.com/rudderlabs/rudder-server/blob/6b0707ff7ab2c384adacdb7d59e8c7a6cbc77828/jobsdb/jobsdb.go#L1172

Fix: The query needs to also specify `usename` in addition to `datname` so that it only finds sessions that are specific to the user being used to access postgres.

**Comment by caseylucas** [comment]
Please let me know if a PR to fix this is welcome and I'll submit one.

**Comment by chandumlg** [comment]
Code to kill connections to DB is removed. This should not happen now.
